services:
    api:
        build: ./api
        ports:
            - "${API_PORT}:5000"
        volumes:
            - ./api:/app
            - /app/node_modules
        env_file:
            - .env
        depends_on:
            - db

    db:
        image: postgres:15
        restart: always
        ports:
            - "${DB_PORT}:5432"
        env_file:
            - .env
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
